import { POSSIBLE_BISHOP_MOVES_RELATIVE_TO_SELECTED_SQUARE } from "./bishop";
import { POSSIBLE_ROOK_MOVES_RELATIVE_TO_SELECTED_SQUARE } from "./rook";

export const POSSIBLE_QUEEN_MOVES_RELATIVE_TO_SELECTED_SQUARE = [
    ...POSSIBLE_ROOK_MOVES_RELATIVE_TO_SELECTED_SQUARE,
    ...POSSIBLE_BISHOP_MOVES_RELATIVE_TO_SELECTED_SQUARE
]