import { Colors, PiecePositions, PieceTypes, SquareColors } from '@/helpers/types';

export function makeFakeChessboard() {
  return [
    [
      {
        position: { row: 0, col: 0 },
        positionOnChessNotation: PiecePositions['a1'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.ROOK, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 0, col: 1 },
        positionOnChessNotation: PiecePositions['a2'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 0, col: 2 },
        positionOnChessNotation: PiecePositions['a3'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 0, col: 3 },
        positionOnChessNotation: PiecePositions['a4'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 0, col: 4 },
        positionOnChessNotation: PiecePositions['a5'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 0, col: 5 },
        positionOnChessNotation: PiecePositions['a6'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 0, col: 6 },
        positionOnChessNotation: PiecePositions['a7'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.WHITE, isFirstMove: true },
      },
      {
        position: { row: 0, col: 7 },
        positionOnChessNotation: PiecePositions['a8'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.ROOK, color: Colors.WHITE, isFirstMove: true },
      },
    ],
    [
      {
        position: { row: 1, col: 0 },
        positionOnChessNotation: PiecePositions['b1'],
        color: Colors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.BISHOP, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 1, col: 1 },
        positionOnChessNotation: PiecePositions['b2'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 1, col: 2 },
        positionOnChessNotation: PiecePositions['b3'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 1, col: 3 },
        positionOnChessNotation: PiecePositions['b4'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 1, col: 4 },
        positionOnChessNotation: PiecePositions['b5'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 1, col: 5 },
        positionOnChessNotation: PiecePositions['b6'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 1, col: 6 },
        positionOnChessNotation: PiecePositions['b7'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.WHITE, isFirstMove: true },
      },
      {
        position: { row: 1, col: 7 },
        positionOnChessNotation: PiecePositions['b8'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.BISHOP, color: Colors.WHITE, isFirstMove: true },
      },
    ],
    [
      {
        position: { row: 2, col: 0 },
        positionOnChessNotation: PiecePositions['c1'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.KNIGHT, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 2, col: 1 },
        positionOnChessNotation: PiecePositions['c2'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 2, col: 2 },
        positionOnChessNotation: PiecePositions['c3'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 2, col: 3 },
        positionOnChessNotation: PiecePositions['c4'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 2, col: 4 },
        positionOnChessNotation: PiecePositions['c5'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 2, col: 5 },
        positionOnChessNotation: PiecePositions['c6'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 2, col: 6 },
        positionOnChessNotation: PiecePositions['c7'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.WHITE, isFirstMove: true },
      },
      {
        position: { row: 2, col: 7 },
        positionOnChessNotation: PiecePositions['c8'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.KNIGHT, color: Colors.WHITE, isFirstMove: true },
      },
    ],
    [
      {
        position: { row: 3, col: 0 },
        positionOnChessNotation: PiecePositions['d1'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.QUEEN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 3, col: 1 },
        positionOnChessNotation: PiecePositions['d2'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 3, col: 2 },
        positionOnChessNotation: PiecePositions['d3'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 3, col: 3 },
        positionOnChessNotation: PiecePositions['d4'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 3, col: 4 },
        positionOnChessNotation: PiecePositions['d5'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 3, col: 5 },
        positionOnChessNotation: PiecePositions['d6'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 3, col: 6 },
        positionOnChessNotation: PiecePositions['d7'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.WHITE, isFirstMove: true },
      },
      {
        position: { row: 3, col: 7 },
        positionOnChessNotation: PiecePositions['d8'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.QUEEN, color: Colors.WHITE, isFirstMove: true },
      },
    ],
    [
      {
        position: { row: 4, col: 0 },
        positionOnChessNotation: PiecePositions['e1'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.KING, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 4, col: 1 },
        positionOnChessNotation: PiecePositions['e2'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 4, col: 2 },
        positionOnChessNotation: PiecePositions['e3'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 4, col: 3 },
        positionOnChessNotation: PiecePositions['e4'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 4, col: 4 },
        positionOnChessNotation: PiecePositions['e5'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 4, col: 5 },
        positionOnChessNotation: PiecePositions['e6'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 4, col: 6 },
        positionOnChessNotation: PiecePositions['e7'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.WHITE, isFirstMove: true },
      },
      {
        position: { row: 4, col: 7 },
        positionOnChessNotation: PiecePositions['e8'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.KING, color: Colors.WHITE, isFirstMove: true },
      },
    ],
    [
      {
        position: { row: 5, col: 0 },
        positionOnChessNotation: PiecePositions['f1'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.KNIGHT, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 5, col: 1 },
        positionOnChessNotation: PiecePositions['f2'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 5, col: 2 },
        positionOnChessNotation: PiecePositions['f3'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 5, col: 3 },
        positionOnChessNotation: PiecePositions['f4'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 5, col: 4 },
        positionOnChessNotation: PiecePositions['f5'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 5, col: 5 },
        positionOnChessNotation: PiecePositions['f6'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 5, col: 6 },
        positionOnChessNotation: PiecePositions['f7'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.WHITE, isFirstMove: true },
      },
      {
        position: { row: 5, col: 7 },
        positionOnChessNotation: PiecePositions['f8'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.KNIGHT, color: Colors.WHITE, isFirstMove: true },
      },
    ],
    [
      {
        position: { row: 6, col: 0 },
        positionOnChessNotation: PiecePositions['g1'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.BISHOP, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 6, col: 1 },
        positionOnChessNotation: PiecePositions['g2'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 6, col: 2 },
        positionOnChessNotation: PiecePositions['g3'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 6, col: 3 },
        positionOnChessNotation: PiecePositions['g4'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 6, col: 4 },
        positionOnChessNotation: PiecePositions['g5'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 6, col: 5 },
        positionOnChessNotation: PiecePositions['g6'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 6, col: 6 },
        positionOnChessNotation: PiecePositions['g7'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.WHITE, isFirstMove: true },
      },
      {
        position: { row: 6, col: 7 },
        positionOnChessNotation: PiecePositions['g8'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.BISHOP, color: Colors.WHITE, isFirstMove: true },
      },
    ],
    [
      {
        position: { row: 7, col: 0 },
        positionOnChessNotation: PiecePositions['h1'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.ROOK, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 7, col: 1 },
        positionOnChessNotation: PiecePositions['h2'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.BLACK, isFirstMove: true },
      },
      {
        position: { row: 7, col: 2 },
        positionOnChessNotation: PiecePositions['h3'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 7, col: 3 },
        positionOnChessNotation: PiecePositions['h4'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 7, col: 4 },
        positionOnChessNotation: PiecePositions['h5'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 7, col: 5 },
        positionOnChessNotation: PiecePositions['h6'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
      },
      {
        position: { row: 7, col: 6 },
        positionOnChessNotation: PiecePositions['h7'],
        color: SquareColors.WHITE,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.PAWN, color: Colors.WHITE, isFirstMove: true },
      },
      {
        position: { row: 7, col: 7 },
        positionOnChessNotation: PiecePositions['h8'],
        color: SquareColors.BLACK,
        isEnemy: false,
        isAttackable: false,
        isPossibleMove: false,
        isOccupied: false,
        piece: { type: PieceTypes.ROOK, color: Colors.WHITE, isFirstMove: true },
      },
    ],
  ];
}
